# Generated by Buildr 1.4.12, change to your liking
# Standard maven2 repository

require 'buildr/checkstyle'
require 'buildr/pmd'
require 'buildr/findbugs'
require 'buildr/java/cobertura'
require 'buildr/javancss'

repositories.remote << 'http://repo1.maven.org/maven2'

desc 'Flux Capacitor'
define 'flux' do
  project.group = 'org.whiskeysierra'
  project.version = '0.1-SNAPSHOT'

  compile.with transitive('com.google.guava:guava:jar:14.0.1'),
      transitive('com.google.code.findbugs:annotations:jar:1.3.9'),
      transitive('com.google.code.findbugs:jsr305:jar:1.3.9'),
      transitive('org.reflections:reflections:jar:0.9.9-RC1'),
      transitive('net.sf.jung:jung-api:jar:2.0.1'),
      transitive('net.sf.jung:jung-graph-impl:jar:2.0.1'),
      transitive('net.sf.jung:jung-algorithms:jar:2.0.1')

  test.with transitive('org.easymock:easymock:jar:3.1'),
      transitive('org.hamcrest:hamcrest-core:jar:1.3')

  pmd.enabled = true

  findbugs.enabled = true

  cobertura.check.line_rate = 100
  cobertura.check.branch_rate = 100

  javancss.enabled = true

  package :jar,
      :id => 'flux'
end
