#!/usr/bin/env python

import os
import sys

current = os.path.dirname(os.path.realpath(__file__))
parent = os.path.dirname(current)

hook = os.path.basename(sys.argv[0])
hooks_directory = os.path.join(parent, 'git-hooks')
hook_directory = os.path.join(hooks_directory, hook + '.d')

try:
    if not os.path.exists(hook_directory):
        sys.exit(0)

    if not os.path.isdir(hook_directory):
        sys.exit(0)

    for script in os.listdir(hook_directory):
        print script

except Exception, e:
    sys.stderr.write('%s\n' % e)
    sys.exit(1)